spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/demo_jpa
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
bonus: 5
my-property: 'my value'
students:
  noms: 'FODE, SELE, CAMARA, Wiyaou'
